### ISSUE TITLE
Click it all the way

### ISSUE THREAD

**Issue by jerguslejko** [matuskropuch/makes-money-all-the-time#1]
In the navigation on left, make sure that you can click whole area, not just a text. Easier to use...

**Comment by matuskropuch** [comment]
resolved in c74469b605c4c639666784f1c65fac1ff13c9d4e

**Comment by jerguslejko** [comment]
mate? what about </li> tags? od macochy?

**Comment by matuskropuch** [comment]
resolved in 0ddcc649af24155adc225dbbec0688008d87ea30
